name: Test
on:
  push:
  pull_request:
 
jobs:
  test_cicero:
    name: Test CICERO with test data
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Determine Short SHA
        run: echo ${{ github.sha }} | tail -c 8 | (read; echo SHORT_SHA=$REPLY) >> $GITHUB_ENV
      -
        name: Sanitize Repo Name for Tagging
        run: echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | (read; echo REPO_LOWER=$REPLY) >> $GITHUB_ENV
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
      - 
        name: Test CICERO
        run: |
          bash test/run_test.sh
